name: notification_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_messaging: ^7.0.3
  shared_preferences: any
  intl: ^0.16.1
  http: ^0.12.2
  flutter_svg: ^0.19.1
  cloud_firestore:
  firebase_auth:
  firebase_core :
  fluttertoast: ^7.1.5
  clipboard_manager: ^0.0.4
  contacts_service: ^0.4.6
  contact_picker: ^0.0.2
  file_picker: ^1.9.0+1
  csv: ^4.0.3
  sms: ^0.2.0
  flutter_slidable: ^0.5.4
  permission_handler: ^4.3.0
  firebase_admin: ^0.1.4
  firebase_storage: ^5.2.0
  custom_switch_button: ^0.5.0
  flutter_speed_dial: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/